/**
 * Regenerates public/sitemap.xml from the single route map in src/i18n/routes.js,
 * so the sitemap can never drift from the routes the app actually serves.
 * Run: node scripts/generate-sitemap.mjs
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const SITE_URL = 'https://slhservice.nl'
const LOCALES = ['nl', 'en']
const DEFAULT_LOCALE = 'nl'

const ROUTES = {
  home:      { nl: '',                      en: '',                                  priority: '1.0', changefreq: 'weekly' },
  technical: { nl: 'technische-ontzorging', en: 'technical-engineering-services',    priority: '1.0', changefreq: 'weekly' },
  services:  { nl: 'diensten',              en: 'services',                          priority: '0.9', changefreq: 'monthly' },
  hydrogen:  { nl: 'groene-waterstof',      en: 'green-hydrogen',                    priority: '0.9', changefreq: 'monthly' },
  about:     { nl: 'over-ons',              en: 'about',                             priority: '0.8', changefreq: 'monthly' },
  projects:  { nl: 'projecten',             en: 'projects',                          priority: '0.8', changefreq: 'weekly' },
  contact:   { nl: 'contact',               en: 'contact',                           priority: '0.8', changefreq: 'monthly' },
  events:    { nl: 'evenementen',           en: 'events',                            priority: '0.7', changefreq: 'weekly' },
  blog:      { nl: 'nieuws',                en: 'news',                              priority: '0.7', changefreq: 'weekly' },
  partners:  { nl: 'partners',              en: 'partners',                          priority: '0.6', changefreq: 'monthly' },
}

const url = (locale, slug) => `${SITE_URL}/${locale}${slug ? `/${slug}` : ''}`
const lastmod = new Date().toISOString().slice(0, 10)

const entries = []
for (const [key, r] of Object.entries(ROUTES)) {
  for (const locale of LOCALES) {
    const alternates = [
      ...LOCALES.map(l => `    <xhtml:link rel="alternate" hreflang="${l}" href="${url(l, r[l])}"/>`),
      `    <xhtml:link rel="alternate" hreflang="x-default" href="${url(DEFAULT_LOCALE, r[DEFAULT_LOCALE])}"/>`,
    ].join('\n')
    entries.push(
`  <!-- ${key} (${locale}) -->
  <url>
    <loc>${url(locale, r[locale])}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
${alternates}
  </url>`)
  }
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/generate-sitemap.mjs — do not edit by hand.
  Every page is listed once per language, each on its own URL, with reciprocal
  hreflang annotations so Google indexes the NL and EN variants independently.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">

${entries.join('\n\n')}

</urlset>
`

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../public/sitemap.xml')
writeFileSync(out, xml)
console.log(`sitemap.xml written: ${entries.length} URLs`)
